[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/api/*"
  to = "https://your-portfolio-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 